print('Hello, world')
print('COZY')
print('ALIEN SUPERSTAR')
print('CUFF IT')
print('ENERGY')
print('BREAK MY SOUL')
print('CHURCH GIRL')
print('PLASTIC OFF THE SOFA')
print('MOVE')
print('HEATED')